### ISSUE TITLE
String styles syntax

### ISSUE THREAD

**Issue by caglarcem** [LansanaCamara/react-native-ghostwriter#3]
Hi, 

Thanks for the nice library. 

I was wondering how I can style the "sequence strings". I followed the doco and added the following **stringStyles**, which doesn't seem to work. What is the correct way to do it?

```
let ghostWriterOptions = {
      sequences: sequences,
      clearEverySequence: true,
      stringStyles: {styles.introText}
}

<View style={styles.container}>
      <Ghostwriter options={ghostWriterOptions} />
</View>
```

**Comment by lansana** [comment]
Hey @caglarcem, thanks!

It looks like you have some styles inside your `ghostWriterOptions`. Styles can only be put in the parent container, but since it's CSS they will cascade into the ghostwriter. So much your `stringStyles` into `styles.container` and it should work as desired.

Let me know if that doesn't resolve it!

**Comment by caglarcem** [comment]
Good to know thanks. Removing curly braces just worked in this case (styles.introText is in a separate file called ApplicationStyles)
Thanks!
